apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app_name }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
  - port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.containerPort }}