apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-crt
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h
  secretName: myctfd-tls-secret
  commonName: myctfd.practice.ru
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
    group: cert-manager.io